### ISSUE TITLE
Possible transition to other MBXPageControllers from childViewController

### ISSUE THREAD

**Issue by daxrahusen** [Moblox/MBXPageViewController#1]
Is it possible to implement a segue from an @IBOutlet in a childViewController to another VC embedded in the MBXPageControllers()?

**Comment by nicarq** [comment]
With the new release that I pushed, you can!. 

https://github.com/Moblox/MBXPageViewController/releases/tag/0.5.3

If you have questions or it's not what you actually needed let me know to see what I can do.
