### ISSUE TITLE
I want Xib into code, but can not add?

### ISSUE THREAD

**Issue by duxinfeng** [Moblox/MBXPageViewController#2]
Hi，Thank you Code！
I want Xib into code, but can not add, I hope to help me.
Thanks again！

@interface AcceptPKViewController () <MBXPageControllerDataSource, MBXPageControllerDataDelegate>
@property (nonatomic, strong) UISegmentedControl _segmentController;
@property (nonatomic, strong) UIView *containerView;
@property (nonatomic, strong) MBXPageViewController_ MBXPageController;

@end

@implementation AcceptPKViewController
- (void)viewDidLoad {
  [super viewDidLoad];
  // Do any additional setup after loading the view.
  
  self.MBXPageController = [[MBXPageViewController alloc] init];
  self.MBXPageController.MBXDataSource = self;
  self.MBXPageController.MBXDataDelegate = self;
  self.MBXPageController.pageMode = MBX_SegmentController;
  [self.MBXPageController reloadPages];

}
# pragma mark - MBXPageViewController Data Source
- (NSArray *)MBXPageButtons
  {
  self.segmentController = [[UISegmentedControl alloc] initWithItems:@[@"BOSS",@"TASK"]];
  self.segmentController.selectedSegmentIndex = 0;
  self.segmentController.highlighted = NO;
  self.segmentController.frame = CGRectMake(10, 5, 300, 35);
  return @[self.segmentController];
  }
- (UIView *)MBXPageContainer
  {
  self.containerView = [[UIView alloc] init];
  self.containerView.frame = DF_FRAME(0, 80, kScreenWidth, 49);
  self.containerView.backgroundColor = [UIColor yellowColor];
  
  return self.containerView;
  }
- (NSArray *)MBXPageControllers
  {
  VisitBossViewController *visitBossViewController = [[VisitBossViewController alloc] init];
  TasksViewController *taskViewController = [[TasksViewController alloc] init];
  
  return @[visitBossViewController,taskViewController];
  }
# pragma mark - MBXPageViewController Delegate
- (void)MBXPageChangedToIndex:(NSInteger)index
  {
  NSLog(@"%@ %ld", [self class], (long)index);
  }

**Comment by nicarq** [comment]
I don't see that you are loading the xib anywhere. It should look like this:

```
// Or Load it from a xib file
    UIViewController *demo2 = [UIViewController new];
    demo2.view = [[[NSBundle mainBundle] loadNibNamed:@"View" owner:self options:nil] objectAtIndex:0];
```

Please check out the example project. I'm going to close this because it's not related to the project.

**Comment by duxinfeng** [comment]
Thanks again, I have solved this problem.

Since my project has no storyboard, so I removed the storyboard in the project. I fork the repo modify the demo was part of the code. https://github.com/duxinfeng/MBXPageViewController

**Comment by nicarq** [comment]
nice!

On Wed, Aug 12, 2015 at 11:39 PM, duxinfeng notifications@github.com
wrote:

> Thanks again, I have solved this problem.
> 
> Since my project has no storyboard, so I removed the project in the
> storyboard. I fork the repo modify the demo was part of the code.
> https://github.com/duxinfeng/MBXPageViewController
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Moblox/MBXPageViewController/issues/2#issuecomment-130520699
> .

## 

Mobile USA: +1 (612) 735 7391
New York: +1 (917) 720 5105
Chile: +56 (2) 2897 4402
Whatsapp: +1 (612) 735 7391
